---
abstract: 'Convert HTML to Txt2tags markup'
author:
  - 'Eric Forgeot'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-WikiConverter-Txt2tags
no_index:
  directory:
    - t
    - inc
requires:
  HTML::WikiConverter: 0.68
version: 0.04
